<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Effect of prior information on transition probabilities and fertilities • raretrans</title>
<!-- jquery --><script src="https://code.jquery.com/jquery-3.1.0.min.js" integrity="sha384-nrOSfDHtoPMzJHjVTdCopGqIqeYETSXhZDFyniQ8ZHcVy08QesyHcnOUpMpqnmWq" crossorigin="anonymous"></script><!-- Bootstrap --><link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script><!-- Font Awesome icons --><link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-T8Gy5hrqNKT+hzMclPo118YTQO6cYprQmhrYwIiQ/3axmI1hQomh7Ud2hPOy8SP1" crossorigin="anonymous">
<!-- pkgdown --><link href="../pkgdown.css" rel="stylesheet">
<script src="../jquery.sticky-kit.min.js"></script><script src="../pkgdown.js"></script><!-- mathjax --><script src="https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script><!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
</head>
<body>
    <div class="container template-vignette">
      <header><div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="../index.html">raretrans</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
<li>
  <a href="../reference/index.html">Reference</a>
</li>
<li>
  <a href="../articles/index.html">Articles</a>
</li>
      </ul>
<ul class="nav navbar-nav navbar-right"></ul>
</div>
<!--/.nav-collapse -->
  </div>
<!--/.container -->
</div>
<!--/.navbar -->

      
      </header><div class="row">
  <div class="col-md-9">
    <div class="page-header toc-ignore">
      <h1>Effect of prior information on transition probabilities and fertilities</h1>
                        <h4 class="author">Drew Tyre</h4>
            
            <h4 class="date">Jun 11, 2018</h4>
          </div>

    
    
<div class="contents">
<div id="borrowing-strength" class="section level2">
<h2 class="hasAnchor">
<a href="#borrowing-strength" class="anchor"></a>Borrowing strength</h2>
<p>Tremblay and McCarthy <span class="citation">(2014)</span> estimated transition probabilities and recruitment rates for another epiphytic orchid from a series of small populations. Although some transitions were not observed in all populations, the presence of a few observations in other populations allowed the statistical models to “borrow strength” from each other and generate estimated probabilities for all transitions. Unfortunately, many (45%; <span class="citation">Salguero-Gómez et al. (2015)</span>) plant demography studies are carried out at single sites or few time periods. In those cases there is no information to fill in the blanks for non-observed transitions.</p>
<p>Here we explore the population consequences of setting a prior accounting for counting constraints. Ignoring the problem treats the transition as a fixed zero. This can have severe consequences for matrix structure <span class="citation">(Stott et al. 2010)</span>. The observed transitions are multinomial rather than binomial events. This can be accommodated by using a Dirichlet prior distribution, albeit at the cost of increased complexity in the calculations. <span class="citation">Eberhardt, Knight, and Blanchard (1986)</span> had a small sample size of grizzlies in some age classes. Morris and Doak <span class="citation">(pg 197, 2002)</span> recognized the potential problem with small sample sizes for rare transitions, but their recommendation is to use the mathematically more complex approach of Tremblay and McCarthy <span class="citation">(2014)</span>. Is there anything that can be done on the simple side?</p>
</div>
<div id="the-matrix" class="section level2">
<h2 class="hasAnchor">
<a href="#the-matrix" class="anchor"></a>The matrix</h2>
<p>We will use observations of an epiphytic Orchid <em>Lepanthes eltoroensis</em> Stimson an endemic species from Puerto Rico <span class="citation">(Tremblay and Hutchings 2003)</span>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(tidyverse)
<span class="kw">library</span>(popbio)
<span class="kw">library</span>(raretrans)

<span class="co"># Raymond's theme modifications</span>
rlt_theme &lt;-<span class="st"> </span><span class="kw">theme</span>(<span class="dt">axis.title.y =</span> <span class="kw">element_text</span>(<span class="dt">colour=</span><span class="st">"grey20"</span>,<span class="dt">size=</span><span class="dv">15</span>,<span class="dt">face=</span><span class="st">"bold"</span>),
        <span class="dt">axis.text.x =</span> <span class="kw">element_text</span>(<span class="dt">colour=</span><span class="st">"grey20"</span>,<span class="dt">size=</span><span class="dv">15</span>, <span class="dt">face=</span><span class="st">"bold"</span>),
        <span class="dt">axis.text.y =</span> <span class="kw">element_text</span>(<span class="dt">colour=</span><span class="st">"grey20"</span>,<span class="dt">size=</span><span class="dv">15</span>,<span class="dt">face=</span><span class="st">"bold"</span>),  
        <span class="dt">axis.title.x =</span> <span class="kw">element_text</span>(<span class="dt">colour=</span><span class="st">"grey20"</span>,<span class="dt">size=</span><span class="dv">15</span>,<span class="dt">face=</span><span class="st">"bold"</span>))
A &lt;-<span class="st"> </span><span class="kw">projection.matrix</span>(<span class="kw">as.data.frame</span>(L_elto), 
                       <span class="dt">stage=</span><span class="st">"stage"</span>, <span class="dt">fate=</span><span class="st">"next_stage"</span>, 
                       <span class="dt">fertility=</span><span class="st">"fertility"</span>, <span class="dt">sort=</span><span class="kw">c</span>(<span class="st">"p"</span>,<span class="st">"j"</span>,<span class="st">"a"</span>))
knitr<span class="op">::</span><span class="kw">kable</span>(A, <span class="dt">digits=</span><span class="dv">2</span>, 
             <span class="dt">caption =</span> <span class="st">"Average transition matrix over all census periods and populations."</span>)</code></pre></div>
<table class="table">
<caption>Average transition matrix over all census periods and populations.</caption>
<thead><tr class="header">
<th></th>
<th align="right">p</th>
<th align="right">j</th>
<th align="right">a</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>p</td>
<td align="right">0.37</td>
<td align="right">0.01</td>
<td align="right">0.05</td>
</tr>
<tr class="even">
<td>j</td>
<td align="right">0.36</td>
<td align="right">0.60</td>
<td align="right">0.01</td>
</tr>
<tr class="odd">
<td>a</td>
<td align="right">0.02</td>
<td align="right">0.10</td>
<td align="right">0.84</td>
</tr>
</tbody>
</table>
<p>Data was collected from 1850 individuals which were permanently identified and tracked over a 6 year period in intervals of 6 months. Thus transitions are for six month intervals and not yearly transitions as is more frequently published. The life history stages included in this analysis are seedlings (individuals without a lepanthiform sheet on any of the leaves), juveniles (individuals with no evidence of present or past reproductive effort, the base of the inflorescence are persistent), and adult (with presence of active or inactive inflorescences). The average population growth rate over all years and populations is 0.86, suggesting a rapid decline.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">plotdata &lt;-<span class="st"> </span>L_elto <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">group_by</span>(POPNUM, year, stage) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">tally</span>() <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">group_by</span>(POPNUM, year) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">summarise</span>(<span class="dt">N =</span> <span class="kw">sum</span>(n))

gg1 &lt;-<span class="st"> </span><span class="kw">ggplot</span>(plotdata, <span class="kw">aes</span>(<span class="dt">x=</span>year, <span class="dt">y=</span>N, <span class="dt">group=</span>POPNUM)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_line</span>() <span class="op">+</span><span class="st"> </span>rlt_theme
plotsumm &lt;-<span class="st"> </span>plotdata <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">group_by</span>(year) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">summarize</span>(<span class="dt">N=</span><span class="kw">sum</span>(N))
gg2 &lt;-<span class="st"> </span><span class="kw">ggplot</span>(plotsumm, <span class="kw">aes</span>(<span class="dt">x=</span>year, <span class="dt">y=</span>N)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_line</span>() <span class="op">+</span><span class="st"> </span>rlt_theme
ggboth &lt;-<span class="st"> </span>gridExtra<span class="op">::</span><span class="kw">grid.arrange</span>(gg1, gg2)

ggboth</code></pre></div>
<pre><code>## TableGrob (2 x 1) "arrange": 2 grobs
##   z     cells    name           grob
## 1 1 (1-1,1-1) arrange gtable[layout]
## 2 2 (2-2,1-1) arrange gtable[layout]</code></pre>
<div class="figure">
<img src="transition_priors_files/figure-html/pop_by_time-1.png" alt="Population size over time." width="480"><p class="caption">
Population size over time.
</p>
</div>
<p>OK, now we want to generate matrices for each year and popnum. We have to change the variables into factors and control the levels so that the resulting matrices end up with the right shape with zeros for the missing transitions. Also have to coerce each grouped tbl_df to a regular data.frame using <code>as.data.frame()</code> before passing to <code>projection.matrix()</code>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">allA &lt;-<span class="st"> </span>L_elto <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">stage =</span> <span class="kw">factor</span>(stage, <span class="dt">levels=</span><span class="kw">c</span>(<span class="st">"p"</span>,<span class="st">"j"</span>,<span class="st">"a"</span>,<span class="st">"m"</span>)),
         <span class="dt">fate =</span> <span class="kw">factor</span>(next_stage, <span class="dt">levels=</span><span class="kw">c</span>(<span class="st">"p"</span>,<span class="st">"j"</span>,<span class="st">"a"</span>,<span class="st">"m"</span>))) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">group_by</span>(POPNUM, year) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">do</span>(<span class="dt">A =</span> <span class="kw">projection.matrix</span>(<span class="kw">as.data.frame</span>(.), 
                           <span class="dt">stage=</span><span class="st">"stage"</span>, <span class="dt">fate=</span><span class="st">"fate"</span>, 
                           <span class="dt">fertility=</span><span class="st">"fertility"</span>, <span class="dt">sort=</span><span class="kw">c</span>(<span class="st">"p"</span>,<span class="st">"j"</span>,<span class="st">"a"</span>)),
     <span class="dt">TF =</span> <span class="kw">projection.matrix</span>(<span class="kw">as.data.frame</span>(.), 
                           <span class="dt">stage=</span><span class="st">"stage"</span>, <span class="dt">fate=</span><span class="st">"fate"</span>, 
                           <span class="dt">fertility=</span><span class="st">"fertility"</span>, <span class="dt">sort=</span><span class="kw">c</span>(<span class="st">"p"</span>,<span class="st">"j"</span>,<span class="st">"a"</span>), <span class="dt">TF =</span> <span class="ot">TRUE</span>),
     <span class="dt">N =</span> <span class="kw"><a href="../reference/get_state_vector.html">get_state_vector</a></span>(<span class="kw">as.data.frame</span>(.), 
                           <span class="dt">stage=</span><span class="st">"stage"</span>, <span class="dt">sort=</span><span class="kw">c</span>(<span class="st">"p"</span>,<span class="st">"j"</span>,<span class="st">"a"</span>))) <span class="op">%&gt;%</span>
<span class="st">  </span>
<span class="st">  </span><span class="kw">filter</span>(year <span class="op">&lt;</span><span class="st"> </span><span class="dv">12</span>) <span class="co"># last time period all zero for obvious reason</span></code></pre></div>
<p>We end up with all the matrices for each population and year in a <code>list-column</code> of the result. Working with this thing is a bit awkward. The best strategy is from <a href="https://speakerdeck.com/jennybc/putting-square-pegs-in-round-holes-using-list-cols-in-your-dataframe">Jenny Bryans’ talk on list columns</a> and uses mutate with map_*(listcolumn, function).</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(popdemo)
allA &lt;-<span class="st"> </span><span class="kw">ungroup</span>(allA) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">A =</span> <span class="kw">map</span>(A, matrix, <span class="dt">nrow=</span><span class="dv">3</span>, <span class="dt">ncol=</span><span class="dv">3</span>,
                 <span class="dt">dimnames=</span><span class="kw">list</span>(<span class="kw">c</span>(<span class="st">"p"</span>,<span class="st">"j"</span>,<span class="st">"a"</span>),<span class="kw">c</span>(<span class="st">"p"</span>,<span class="st">"j"</span>,<span class="st">"a"</span>)))) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">lmbda =</span> <span class="kw">map_dbl</span>(A, lambda),
         <span class="dt">ergodic =</span> <span class="kw">map_dbl</span>(A, is.matrix_ergodic),
         <span class="dt">irreduc =</span> <span class="kw">map_dbl</span>(A, is.matrix_irreducible),
         <span class="dt">primitv =</span> <span class="kw">map_dbl</span>(A, is.matrix_primitive))
<span class="kw">ggplot</span>(allA, <span class="kw">aes</span>(<span class="dt">x=</span>lmbda)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_histogram</span>() <span class="op">+</span><span class="st"> </span><span class="kw">facet_wrap</span>(<span class="op">~</span>year)<span class="op">+</span>
<span class="st"> </span><span class="kw">ylab</span>(<span class="st">"Frequency"</span>)<span class="op">+</span>
<span class="st">  </span><span class="kw">xlab</span>(<span class="kw">expression</span>(<span class="kw">paste</span>(lambda, <span class="st">", asymptotic population growth"</span>))) <span class="op">+</span><span class="st"> </span>rlt_theme</code></pre></div>
<div class="figure">
<img src="transition_priors_files/figure-html/histLmbdaByYear-1.png" alt="histograms of asymptotic population growth for each year." width="480"><p class="caption">
histograms of asymptotic population growth for each year.
</p>
</div>
<p>Now, we need to figure out how many matrices are missing transitions. The full matrix has observed transitions in every cell.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">allA &lt;-<span class="st"> </span><span class="kw">ungroup</span>(allA) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mutate</span>(<span class="dt">missing =</span> <span class="kw">map</span>(A, <span class="op">~</span><span class="kw">which</span>(.x<span class="op">==</span><span class="dv">0</span>)),
                                 <span class="dt">n_missing =</span> <span class="kw">map_dbl</span>(missing, length))
missing_summary &lt;-<span class="st"> </span><span class="kw">summary</span>(allA<span class="op">$</span>n_missing)
ergo_irr &lt;-<span class="st"> </span><span class="kw">as.data.frame</span>(<span class="kw">with</span>(allA, <span class="kw">table</span>(ergodic, irreduc)))
knitr<span class="op">::</span><span class="kw">kable</span>(ergo_irr, <span class="dt">caption =</span> <span class="st">"Ergodicity and irreducibility of individual transition matrices."</span>)</code></pre></div>
<table class="table">
<caption>Ergodicity and irreducibility of individual transition matrices.</caption>
<thead><tr class="header">
<th align="left">ergodic</th>
<th align="left">irreduc</th>
<th align="right">Freq</th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="left">0</td>
<td align="left">0</td>
<td align="right">215</td>
</tr>
<tr class="even">
<td align="left">1</td>
<td align="left">0</td>
<td align="right">17</td>
</tr>
<tr class="odd">
<td align="left">0</td>
<td align="left">1</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">1</td>
<td align="left">1</td>
<td align="right">6</td>
</tr>
</tbody>
</table>
<p>Out of 11 time periods and 23 populations there are a total of 238 transition matrices. Some periods are missing for some populations. Only 6 of these matrices are irreducible. All of the matrices have 2 or more transitions that are zero but known to be possible.</p>
<table class="table">
<caption>Two problematic matrices and the matrix with the largest sample size; <span class="math inline">\(\lambda\)</span> = 0, 1, and 0.92 for population 905, 914 and 205 respectively. The six columns on the right show the effect of assuming a uniform prior for transitions with a total weight of 1, and an RLT prior with total weight equal to 1. Where columns do not sum to 1 the remaining probability represents mortality.</caption>
<thead><tr class="header">
<th align="right">Population</th>
<th align="right">Year</th>
<th align="left">Stage</th>
<th align="right">N</th>
<th align="right">seedling</th>
<th align="right">juvenile</th>
<th align="right">adult</th>
<th align="right">seedling1</th>
<th align="right">juvenile1</th>
<th align="right">adult1</th>
<th align="right">seedling2</th>
<th align="right">juvenile2</th>
<th align="right">adult2</th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="right">905</td>
<td align="right">9</td>
<td align="left">seedling</td>
<td align="right">0</td>
<td align="right">0.000</td>
<td align="right">0.000</td>
<td align="right">0.000</td>
<td align="right">0.250</td>
<td align="right">0.042</td>
<td align="right">0.042</td>
<td align="right">0.250</td>
<td align="right">0.004</td>
<td align="right">0.000</td>
</tr>
<tr class="even">
<td align="right">905</td>
<td align="right">9</td>
<td align="left">juvenile</td>
<td align="right">5</td>
<td align="right">0.000</td>
<td align="right">0.000</td>
<td align="right">0.000</td>
<td align="right">0.250</td>
<td align="right">0.042</td>
<td align="right">0.042</td>
<td align="right">0.050</td>
<td align="right">0.150</td>
<td align="right">0.004</td>
</tr>
<tr class="odd">
<td align="right">905</td>
<td align="right">9</td>
<td align="left">adult</td>
<td align="right">5</td>
<td align="right">0.000</td>
<td align="right">0.000</td>
<td align="right">0.000</td>
<td align="right">0.250</td>
<td align="right">0.042</td>
<td align="right">0.042</td>
<td align="right">0.010</td>
<td align="right">0.004</td>
<td align="right">0.158</td>
</tr>
<tr class="even">
<td align="right">914</td>
<td align="right">6</td>
<td align="left">seedling</td>
<td align="right">2</td>
<td align="right">0.500</td>
<td align="right">0.000</td>
<td align="right">0.000</td>
<td align="right">0.417</td>
<td align="right">0.125</td>
<td align="right">0.042</td>
<td align="right">0.417</td>
<td align="right">0.012</td>
<td align="right">0.000</td>
</tr>
<tr class="odd">
<td align="right">914</td>
<td align="right">6</td>
<td align="left">juvenile</td>
<td align="right">1</td>
<td align="right">0.000</td>
<td align="right">0.000</td>
<td align="right">0.000</td>
<td align="right">0.083</td>
<td align="right">0.125</td>
<td align="right">0.042</td>
<td align="right">0.017</td>
<td align="right">0.450</td>
<td align="right">0.004</td>
</tr>
<tr class="even">
<td align="right">914</td>
<td align="right">6</td>
<td align="left">adult</td>
<td align="right">5</td>
<td align="right">0.000</td>
<td align="right">1.000</td>
<td align="right">1.000</td>
<td align="right">0.083</td>
<td align="right">0.625</td>
<td align="right">0.875</td>
<td align="right">0.003</td>
<td align="right">0.512</td>
<td align="right">0.992</td>
</tr>
<tr class="odd">
<td align="right">250</td>
<td align="right">5</td>
<td align="left">seedling</td>
<td align="right">11</td>
<td align="right">0.091</td>
<td align="right">0.000</td>
<td align="right">0.118</td>
<td align="right">0.104</td>
<td align="right">0.005</td>
<td align="right">0.007</td>
<td align="right">0.104</td>
<td align="right">0.001</td>
<td align="right">0.000</td>
</tr>
<tr class="even">
<td align="right">250</td>
<td align="right">5</td>
<td align="left">juvenile</td>
<td align="right">47</td>
<td align="right">0.636</td>
<td align="right">0.574</td>
<td align="right">0.000</td>
<td align="right">0.604</td>
<td align="right">0.568</td>
<td align="right">0.007</td>
<td align="right">0.588</td>
<td align="right">0.581</td>
<td align="right">0.001</td>
</tr>
<tr class="odd">
<td align="right">250</td>
<td align="right">5</td>
<td align="left">adult</td>
<td align="right">34</td>
<td align="right">0.000</td>
<td align="right">0.298</td>
<td align="right">0.853</td>
<td align="right">0.021</td>
<td align="right">0.297</td>
<td align="right">0.836</td>
<td align="right">0.001</td>
<td align="right">0.292</td>
<td align="right">0.856</td>
</tr>
</tbody>
</table>
</div>
<div id="ignore-the-problem" class="section level2">
<h2 class="hasAnchor">
<a href="#ignore-the-problem" class="anchor"></a>Ignore the problem</h2>
<p>Ignoring this problem and calculating stochastic <span class="math inline">\(\lambda\)</span> for each population could yield non-sensical results. For example, the geometric mean <span class="math inline">\(\lambda\)</span> calculated using simulation fails for 6 out of the 23 populations. These are the populations with one matrix that has <span class="math inline">\(\lambda = 0\)</span> at some point.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">sgr &lt;-<span class="st"> </span>allA <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">split</span>(.<span class="op">$</span>POPNUM) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">map</span>(<span class="op">~</span><span class="kw">stoch.growth.rate</span>(.x<span class="op">$</span>A, <span class="dt">verbose =</span> <span class="ot">FALSE</span>))

<span class="co"># distribute results of stoch.growth.rate() into a tbl</span>
xtrc &lt;-<span class="st"> </span><span class="cf">function</span>(x){
  <span class="kw">data.frame</span>(<span class="dt">approx=</span>x<span class="op">$</span>approx,
                <span class="dt">sim =</span> x<span class="op">$</span>sim,
                <span class="dt">lowerci =</span> x<span class="op">$</span>sim.CI[<span class="dv">1</span>],
                <span class="dt">upperci =</span> x<span class="op">$</span>sim.CI[<span class="dv">2</span>])
}
sgr &lt;-<span class="st"> </span><span class="kw">bind_rows</span>(<span class="kw">map</span>(sgr, xtrc), <span class="dt">.id=</span><span class="st">"POPNUM"</span>) 
<span class="kw">filter</span>(sgr, <span class="op">!</span><span class="kw">is.na</span>(sim)) <span class="op">%&gt;%</span>
<span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x=</span>approx, <span class="dt">y =</span> sim)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">geom_errorbar</span>(<span class="kw">aes</span>(<span class="dt">ymin=</span>lowerci, <span class="dt">ymax=</span>upperci)) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">geom_abline</span>(<span class="dt">slope =</span> <span class="dv">1</span>, <span class="dt">intercept=</span><span class="dv">0</span>) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span>rlt_theme <span class="op">+</span>
<span class="st">  </span><span class="kw">xlab</span>(<span class="kw">expression</span>(<span class="kw">paste</span>(<span class="st">"Tuljapurkar's approximate stochastic "</span>, <span class="kw">log</span>(lambda)))) <span class="op">+</span>
<span class="st">  </span><span class="kw">ylab</span>(<span class="kw">expression</span>(<span class="kw">paste</span>(<span class="st">"Stochastic "</span>, <span class="kw">log</span>(lambda), <span class="st">" by simulation"</span>)))</code></pre></div>
<div class="figure">
<img src="transition_priors_files/figure-html/stochGrowthRateBad-1.png" alt="Stochastic population growth rates for 17 out of 23 orchid populations. " width="480"><p class="caption">
Stochastic population growth rates for 17 out of 23 orchid populations.
</p>
</div>
<p>The six populations where the simulated values are unavailable have very low approximate growth rates as well. All the stochastic growth rates are less than 1. Note that these calculations assume each matrix is perfectly observed; the only stochasticity is between year environmental stochasticity as represented by the observed sample of years.</p>
</div>
<div id="fill-in-including-constraints-on-transitions" class="section level2">
<h2 class="hasAnchor">
<a href="#fill-in-including-constraints-on-transitions" class="anchor"></a>Fill in including constraints on transitions</h2>
<p>This strategy uses the transitions in a smarter way that maintains the constraint that all survival/transition probabilities have to add up to 1. We do this by using a dirichlet prior with the function <code><a href="../reference/fill_transitions.html">fill_transitions()</a></code>. This function takes the matrix as a list of 2 components, a matrix of transition probabilities <span class="math inline">\(T\)</span> and a matrix of fertility contributions <span class="math inline">\(F\)</span>. The Dirichlet prior only applies to the <span class="math inline">\(T\)</span> matrix. If not specified, the function assumes a uniform prior across the <span class="math inline">\(m+1\)</span> fates for each stage. The extra category is for individuals that do not survive. Let’s look at a single example to see how it works, using population 231 in period 1. This matrix is non-ergodic and reducible, and there are individuals in every stage.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># </span>
tmat &lt;-<span class="st"> </span>allA[<span class="dv">23</span>,<span class="st">"TF"</span>][[<span class="dv">1</span>]][[<span class="dv">1</span>]]<span class="op">$</span>T ## wow! hard to get at ... 
fmat &lt;-<span class="st"> </span>allA[<span class="dv">23</span>,<span class="st">"TF"</span>][[<span class="dv">1</span>]][[<span class="dv">1</span>]]<span class="op">$</span>F
N &lt;-<span class="st"> </span>allA[<span class="dv">23</span>,<span class="st">"N"</span>][[<span class="dv">1</span>]][[<span class="dv">1</span>]]
tmat <span class="op">+</span><span class="st"> </span>fmat</code></pre></div>
<pre><code>##    
##          p      j      a
##   p 0.0000 0.0000 0.1250
##   j 0.0000 0.0000 0.0000
##   a 1.0000 0.0000 0.9375</code></pre>
<p>The matrix is reducible because the 2nd column and 2nd row could be eliminated without affecting population growth; this is because the 2 juveniles died. The matrix is not ergodic because there is no path from the 2nd stage to either of the other stages.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">is.matrix_ergodic</span>((tmat <span class="op">+</span><span class="st"> </span>fmat)[<span class="op">-</span><span class="dv">2</span>,<span class="op">-</span><span class="dv">2</span>])</code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">is.matrix_irreducible</span>((tmat <span class="op">+</span><span class="st"> </span>fmat)[<span class="op">-</span><span class="dv">2</span>,<span class="op">-</span><span class="dv">2</span>])</code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">all.equal</span>(<span class="kw">lambda</span>((tmat <span class="op">+</span><span class="st"> </span>fmat)[<span class="op">-</span><span class="dv">2</span>,<span class="op">-</span><span class="dv">2</span>]), <span class="kw">lambda</span>(tmat <span class="op">+</span><span class="st"> </span>fmat))</code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<p>So, to add a dirichlet prior with a weight of 1 to <span class="math inline">\(T\)</span>, we have 4 fates (3 + death), so each fate adds 0.25.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">(tmat2 &lt;-<span class="st"> </span>tmat <span class="op">+</span><span class="st"> </span><span class="fl">0.25</span>) <span class="co"># re-cycles automatically</span></code></pre></div>
<pre><code>##    
##          p      j      a
##   p 0.2500 0.2500 0.2500
##   j 0.2500 0.2500 0.2500
##   a 1.2500 0.2500 1.1875</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">lambda</span>(tmat2 <span class="op">+</span><span class="st"> </span>fmat)</code></pre></div>
<pre><code>## [1] 1.637685</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">is.matrix_ergodic</span>(tmat2 <span class="op">+</span><span class="st"> </span>fmat)</code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">is.matrix_irreducible</span>(tmat2 <span class="op">+</span><span class="st"> </span>fmat)</code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<p>This case is the largest distortion (<span class="math inline">\(\lambda\)</span> increase from 1.06 to 1.64) observed from a uniform prior for any of the matrices.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">testing &lt;-<span class="st"> </span>allA <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mutate</span>(<span class="dt">Adirch =</span> <span class="kw">map2</span>(TF, N, fill_transitions),
                           <span class="dt">ldirch =</span> <span class="kw">map_dbl</span>(Adirch, lambda),                 
         <span class="dt">irrdirch =</span> <span class="kw">map_dbl</span>(Adirch, is.matrix_irreducible),
         <span class="dt">ergdirch =</span> <span class="kw">map_dbl</span>(Adirch, is.matrix_ergodic),
         <span class="dt">TN =</span> <span class="kw">map2</span>(TF, N, fill_transitions, <span class="dt">returnType =</span> <span class="st">"TN"</span>))

<span class="kw">ggplot</span>(testing, <span class="kw">aes</span>(<span class="dt">x=</span>lmbda, <span class="dt">y=</span>ldirch)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">geom_abline</span>(<span class="dt">slope =</span> <span class="dv">1</span>, <span class="dt">intercept=</span><span class="dv">0</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">xlab</span>(<span class="kw">expression</span>(<span class="kw">paste</span>(lambda, <span class="st">" ignoring zeros"</span>))) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">ylab</span>(<span class="kw">expression</span>(<span class="kw">paste</span>(lambda, <span class="st">" using a uniform prior"</span>))) <span class="op">+</span>
<span class="st">  </span>rlt_theme</code></pre></div>
<div class="figure">
<img src="transition_priors_files/figure-html/fillDirichlet-1.png" alt="Asymptotic growth rate using a uniform prior with a total weight of 1 vs. the asymptotic growth rate for the observed data." width="480"><p class="caption">
Asymptotic growth rate using a uniform prior with a total weight of 1 vs. the asymptotic growth rate for the observed data.
</p>
</div>
<p>The matrices with <span class="math inline">\(\lambda = 0\)</span> typically have very few individuals that all die. Matrices with <span class="math inline">\(\lambda = 1\)</span> usually have observed transitions only on the main diagonal.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">ergo_irr &lt;-<span class="st"> </span><span class="kw">as.data.frame</span>(<span class="kw">with</span>(testing, <span class="kw">table</span>(ergdirch, irrdirch)))

knitr<span class="op">::</span><span class="kw">kable</span>(ergo_irr, <span class="dt">caption =</span> <span class="st">"Ergodicity and irreducibility of individual transition matrices."</span>)</code></pre></div>
<table class="table">
<caption>Ergodicity and irreducibility of individual transition matrices.</caption>
<thead><tr class="header">
<th align="left">ergdirch</th>
<th align="left">irrdirch</th>
<th align="right">Freq</th>
</tr></thead>
<tbody><tr class="odd">
<td align="left">1</td>
<td align="left">1</td>
<td align="right">238</td>
</tr></tbody>
</table>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">sgr_unif &lt;-<span class="st"> </span>testing <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">split</span>(.<span class="op">$</span>POPNUM) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">map</span>(<span class="op">~</span><span class="kw">stoch.growth.rate</span>(.x<span class="op">$</span>Adirch, <span class="dt">verbose =</span> <span class="ot">FALSE</span>))

sgr_unif &lt;-<span class="st"> </span><span class="kw">bind_rows</span>(<span class="kw">map</span>(sgr_unif, xtrc), <span class="dt">.id=</span><span class="st">"POPNUM"</span>) 
compare_approx &lt;-<span class="st"> </span><span class="kw">data_frame</span>(<span class="dt">unif =</span> sgr_unif<span class="op">$</span>approx,
                             <span class="dt">ignored =</span> sgr<span class="op">$</span>approx)
<span class="kw">ggplot</span>(compare_approx, <span class="kw">aes</span>(<span class="dt">x=</span>ignored, <span class="dt">y =</span> unif)) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">geom_abline</span>(<span class="dt">slope =</span> <span class="dv">1</span>, <span class="dt">intercept=</span><span class="dv">0</span>) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">xlab</span>(<span class="kw">expression</span>(<span class="kw">paste</span>(<span class="st">"log("</span>,lambda,<span class="st">") ignoring zeros"</span>))) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">ylab</span>(<span class="kw">expression</span>(<span class="kw">paste</span>(<span class="st">"log("</span>,lambda,<span class="st">") with uniform prior"</span>))) <span class="op">+</span>
<span class="st">  </span>rlt_theme</code></pre></div>
<p><img src="transition_priors_files/figure-html/stochDirchVsBad-1.png" width="480"></p>
<p>So using a Dirichlet prior to fill in the gaps works, and doesn’t appear to distort the stochastic population growth rate; all populations still have negative growth. Most populations end up with stochastic growth rates that are lower than with the problematic matrices. All resulting matrices are now ergodic and irreducible.</p>
</div>
<div id="fill-in-using-uninformative-priors-on-fertility" class="section level2">
<h2 class="hasAnchor">
<a href="#fill-in-using-uninformative-priors-on-fertility" class="anchor"></a>Fill in using uninformative priors on fertility</h2>
<p>The other component of the matrix is the fertility. We do this by using a Gamma prior with the function <code><a href="../reference/fill_fecundity.html">fill_fecundity()</a></code>. This function takes the matrix as a list of 2 components, a matrix of transition probabilities <span class="math inline">\(T\)</span> and a matrix of fertility contributions <span class="math inline">\(F\)</span>. The Gamma prior only applies to the <span class="math inline">\(F\)</span> matrix. If not specified, the function assumes an uniformative prior with <span class="math inline">\(\alpha = 0.00001, \beta = 0.00001\)</span> across all stages. Stages that do not reproduce are marked with <code>NA_real_</code> in the prior probability vectors.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">testing &lt;-<span class="st"> </span>allA <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mutate</span>(<span class="dt">Agamma =</span> <span class="kw">map2</span>(TF, N, fill_fecundity, <span class="dt">alpha =</span> <span class="kw">c</span>(<span class="ot">NA_real_</span>, <span class="ot">NA_real_</span>, <span class="fl">0.00001</span>), <span class="dt">beta =</span> <span class="kw">c</span>(<span class="ot">NA_real_</span>, <span class="ot">NA_real_</span>, <span class="fl">0.00001</span>), <span class="dt">priorweight =</span> <span class="dv">1</span>),
                           <span class="dt">lgamma =</span> <span class="kw">map_dbl</span>(Agamma, lambda),                 
         <span class="dt">irrgamma =</span> <span class="kw">map_dbl</span>(Agamma, is.matrix_irreducible),
         <span class="dt">erggamma =</span> <span class="kw">map_dbl</span>(Agamma, is.matrix_ergodic))

<span class="kw">ggplot</span>(testing, <span class="kw">aes</span>(<span class="dt">x=</span>lmbda, <span class="dt">y=</span>lgamma)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">geom_abline</span>(<span class="dt">slope =</span> <span class="dv">1</span>, <span class="dt">intercept=</span><span class="dv">0</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">xlab</span>(<span class="kw">expression</span>(<span class="kw">paste</span>(lambda, <span class="st">" ignoring zeros"</span>))) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">ylab</span>(<span class="kw">expression</span>(<span class="kw">paste</span>(lambda, <span class="st">" using an uninformative prior"</span>))) <span class="op">+</span>
<span class="st">  </span>rlt_theme</code></pre></div>
<div class="figure">
<img src="transition_priors_files/figure-html/fillGamma-1.png" alt="Asymptotic growth rate using a uniform prior with a total weight of 1 vs. the asymptotic growth rate for the observed data." width="480"><p class="caption">
Asymptotic growth rate using a uniform prior with a total weight of 1 vs. the asymptotic growth rate for the observed data.
</p>
</div>
<p>The matrices with <span class="math inline">\(\lambda = 0\)</span> typically have very few individuals. Matrices with <span class="math inline">\(\lambda = 1\)</span> usually have transitions only on the main diagonal. The uninformative Gamma prior does not change <span class="math inline">\(\lambda\)</span>, and does not improve the ergodicity and irreducibility issue. When there is at least 1 adult present, the expected value of Fecundity is very close to zero. When there are no adults present, all those matrices cannot reach the adult stage and so the expected value of Fecundity does not affect <span class="math inline">\(\lambda\)</span>. However, this is not a necessary condition.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">ergo_irr &lt;-<span class="st"> </span><span class="kw">as.data.frame</span>(<span class="kw">with</span>(testing, <span class="kw">table</span>(erggamma, irrgamma)))

knitr<span class="op">::</span><span class="kw">kable</span>(ergo_irr, <span class="dt">caption =</span> <span class="st">"Ergodicity and irreducibility of individual transition matrices."</span>)</code></pre></div>
<table class="table">
<caption>Ergodicity and irreducibility of individual transition matrices.</caption>
<thead><tr class="header">
<th align="left">erggamma</th>
<th align="left">irrgamma</th>
<th align="right">Freq</th>
</tr></thead>
<tbody><tr class="odd">
<td align="left">0</td>
<td align="left">0</td>
<td align="right">238</td>
</tr></tbody>
</table>
</div>
<div id="effects-of-informative-priors" class="section level2">
<h2 class="hasAnchor">
<a href="#effects-of-informative-priors" class="anchor"></a>Effects of informative priors</h2>
<p>We extracted an informative prior from an expert on epiphytic orchids (RLT) to compare with the uniform prior. In particular, we considered the effects of weighting the prior by different fractions of the actual sample size for each population and year.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">RLT_Tprior &lt;-<span class="st"> </span><span class="kw">matrix</span>(<span class="kw">c</span>(<span class="fl">0.25</span>, <span class="fl">0.025</span>, <span class="fl">0.0</span>,
                       <span class="fl">0.05</span>, <span class="fl">0.9</span>,   <span class="fl">0.025</span>,
                       <span class="fl">0.01</span>, <span class="fl">0.025</span>, <span class="fl">0.95</span>,
                       <span class="fl">0.69</span>, <span class="fl">0.05</span>,  <span class="fl">0.025</span>), 
                     <span class="dt">byrow =</span> <span class="ot">TRUE</span>, <span class="dt">nrow =</span> <span class="dv">4</span>, <span class="dt">ncol =</span> <span class="dv">3</span>)
RLT_Fprior &lt;-<span class="st"> </span><span class="kw">matrix</span>(<span class="kw">c</span>(<span class="fl">0.0</span>, <span class="fl">0.0</span>, <span class="fl">0.025</span>,
                       <span class="fl">0.0</span>, <span class="fl">0.0</span>, <span class="fl">0.0</span>,
                       <span class="fl">0.0</span>, <span class="fl">0.0</span>, <span class="fl">0.0</span>), 
                     <span class="dt">byrow =</span> <span class="ot">TRUE</span>, <span class="dt">nrow =</span> <span class="dv">3</span>, <span class="dt">ncol =</span> <span class="dv">3</span>)</code></pre></div>
<p>The RLT prior gives <span class="math inline">\(\lambda = 0.96\)</span>. In an ideal world this prior would be extracted prior to collecting the data. In this case the prior is only being used to demonstrate the technique.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">diffPriors &lt;-<span class="st"> </span><span class="kw">list</span>()
diffPriors[[<span class="st">"Uniform"</span>]] &lt;-<span class="st"> </span>testing <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">Tprior =</span> <span class="kw">map2</span>(TF, N, fill_transitions, <span class="dt">returnType =</span> <span class="st">"T"</span>),
         <span class="dt">Fprior =</span> <span class="kw">map2</span>(TF, N, fill_fecundity,
                       <span class="dt">alpha =</span> <span class="kw">c</span>(<span class="ot">NA_real_</span>, <span class="ot">NA_real_</span>, <span class="fl">0.00001</span>),
                       <span class="dt">beta =</span> <span class="kw">c</span>(<span class="ot">NA_real_</span>, <span class="ot">NA_real_</span>, <span class="fl">0.00001</span>), <span class="dt">priorweight =</span> <span class="dv">1</span>, <span class="dt">returnType =</span> <span class="st">"F"</span>),
         <span class="dt">Aprior =</span> <span class="kw">map2</span>(Tprior, Fprior, <span class="st">`</span><span class="dt">+</span><span class="st">`</span>),
         <span class="dt">lprior =</span> <span class="kw">map_dbl</span>(Aprior, lambda))


diffPriors[[<span class="st">"RLT, weight = 1"</span>]] &lt;-<span class="st"> </span>testing <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">Tprior =</span> <span class="kw">map2</span>(TF, N, fill_transitions, 
                       <span class="dt">P =</span> RLT_Tprior, <span class="dt">returnType =</span> <span class="st">"T"</span>),
         <span class="dt">Fprior =</span> <span class="kw">map2</span>(TF, N, fill_fecundity,
                       <span class="dt">alpha =</span> <span class="kw">c</span>(<span class="ot">NA_real_</span>, <span class="ot">NA_real_</span>, <span class="fl">0.025</span>),
                       <span class="dt">beta =</span> <span class="kw">c</span>(<span class="ot">NA_real_</span>, <span class="ot">NA_real_</span>, <span class="dv">1</span>), <span class="dt">priorweight =</span> <span class="dv">1</span>, <span class="dt">returnType =</span> <span class="st">"F"</span>),
         <span class="dt">Aprior =</span> <span class="kw">map2</span>(Tprior, Fprior, <span class="st">`</span><span class="dt">+</span><span class="st">`</span>),
         <span class="dt">lprior =</span> <span class="kw">map_dbl</span>(Aprior, lambda))

diffPriors[[<span class="st">"RLT, weight = 0.5N"</span>]] &lt;-<span class="st"> </span>testing <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">Tprior =</span> <span class="kw">map2</span>(TF, N, fill_transitions, 
                       <span class="dt">P =</span> RLT_Tprior, <span class="dt">priorweight =</span> <span class="fl">0.5</span>, <span class="dt">returnType =</span> <span class="st">"T"</span>),
         <span class="dt">Fprior =</span> <span class="kw">map2</span>(TF, N, fill_fecundity,
                       <span class="dt">alpha =</span> <span class="kw">c</span>(<span class="ot">NA_real_</span>, <span class="ot">NA_real_</span>, <span class="fl">0.025</span>),
                       <span class="dt">beta =</span> <span class="kw">c</span>(<span class="ot">NA_real_</span>, <span class="ot">NA_real_</span>, <span class="dv">1</span>), <span class="dt">priorweight =</span> <span class="fl">0.5</span>, <span class="dt">returnType =</span> <span class="st">"F"</span>),
         <span class="dt">Aprior =</span> <span class="kw">map2</span>(Tprior, Fprior, <span class="st">`</span><span class="dt">+</span><span class="st">`</span>),
         <span class="dt">lprior =</span> <span class="kw">map_dbl</span>(Aprior, lambda))

diffPriors[[<span class="st">"RLT, weight = N"</span>]] &lt;-<span class="st"> </span>testing <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">Tprior =</span> <span class="kw">map2</span>(TF, N, fill_transitions, 
                       <span class="dt">P =</span> RLT_Tprior, <span class="dt">priorweight =</span> <span class="dv">1</span>, <span class="dt">returnType =</span> <span class="st">"T"</span>),
         <span class="dt">Fprior =</span> <span class="kw">map2</span>(TF, N, fill_fecundity,
                       <span class="dt">alpha =</span> <span class="kw">c</span>(<span class="ot">NA_real_</span>, <span class="ot">NA_real_</span>, <span class="fl">0.025</span>),
                       <span class="dt">beta =</span> <span class="kw">c</span>(<span class="ot">NA_real_</span>, <span class="ot">NA_real_</span>, <span class="dv">1</span>), <span class="dt">priorweight =</span> <span class="dv">1</span>, <span class="dt">returnType =</span> <span class="st">"F"</span>),
         <span class="dt">Aprior =</span> <span class="kw">map2</span>(Tprior, Fprior, <span class="st">`</span><span class="dt">+</span><span class="st">`</span>),
         <span class="dt">lprior =</span> <span class="kw">map_dbl</span>(Aprior, lambda))

diffPriors &lt;-<span class="st"> </span><span class="kw">bind_rows</span>(diffPriors, <span class="dt">.id=</span><span class="st">"prior"</span>)
diffPriors<span class="op">$</span>prior &lt;-<span class="st"> </span><span class="kw">factor</span>(diffPriors<span class="op">$</span>prior, <span class="dt">levels =</span> <span class="kw">c</span>(<span class="st">"Uniform"</span>, <span class="st">"RLT, weight = 1"</span>,
                                                        <span class="st">"RLT, weight = 0.5N"</span>, <span class="st">"RLT, weight = N"</span>))
<span class="kw">ggplot</span>(diffPriors, <span class="kw">aes</span>(<span class="dt">x=</span>lmbda, <span class="dt">y=</span>lprior)) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">geom_point</span>(<span class="dt">data=</span><span class="kw">select</span>(diffPriors, <span class="op">-</span>prior), <span class="dt">alpha=</span><span class="fl">0.1</span>) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">geom_abline</span>(<span class="dt">slope =</span> <span class="dv">1</span>, <span class="dt">intercept=</span><span class="dv">0</span>, <span class="dt">linetype =</span> <span class="dv">2</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">ylab</span>(<span class="kw">expression</span>(<span class="kw">paste</span>(lambda, <span class="st">" including prior information"</span>))) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">xlab</span>(<span class="kw">expression</span>(<span class="kw">paste</span>(lambda, <span class="st">" from raw observations"</span>))) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">facet_wrap</span>(<span class="op">~</span>prior) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">geom_hline</span>(<span class="dt">yintercept =</span> <span class="fl">0.96</span>, <span class="dt">color=</span><span class="st">"red"</span>, <span class="dt">linetype =</span> <span class="dv">2</span> ) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">theme_bw</span>() <span class="op">+</span><span class="st"> </span>rlt_theme</code></pre></div>
<div class="figure">
<img src="transition_priors_files/figure-html/fillDirichletPrior1-1.png" alt="Asymptotic growth rates using prior information on transitions and fecundity vs. the raw observations alone. The horizontal red line indicates $\lambda$ for the RLT prior. Points for all four priors shown in transparent grey." width="480"><p class="caption">
Asymptotic growth rates using prior information on transitions and fecundity vs. the raw observations alone. The horizontal red line indicates <span class="math inline">\(\lambda\)</span> for the RLT prior. Points for all four priors shown in transparent grey.
</p>
</div>
</div>
<div id="obtaining-credible-intervals-on-vital-rates-and-lambda" class="section level1">
<h1 class="hasAnchor">
<a href="#obtaining-credible-intervals-on-vital-rates-and-lambda" class="anchor"></a>Obtaining credible intervals on vital rates and <span class="math inline">\(\lambda\)</span>
</h1>
<p>Recognizing that the observed transitions are realizations of a Dirichlet distribution gives us a very simple way to derive credible intervals for the transition probabilities in our matrix. The marginal distribution of a single transition is a beta distribution as described above, and we can simply report the 2.5% and 97.5% percentiles of that distribution to provide a credible interval on a transition rate. These intervals do shift and shrink as the weight on the prior increases.</p>
<div class="figure">
<img src="transition_priors_files/figure-html/credibleIntervals1-1.png" alt="Confidence limits or Credible intervals for transition probabilities out of seedling stage in Population 250, year 5. Shaded bands correspond to 50% (darkest), 90%, 95% and 99.9% (lightest) credible intervals. Smaller intervals are not visible in the p-&gt;a transitions when the upper boundary of the interval is smaller than 0.01. Labels are median (lower 95% CI, upper 95% CI). Note that where the median and lower interval are equal to 0.001, the actual value is &lt; 0.001." width="672"><p class="caption">
Confidence limits or Credible intervals for transition probabilities out of seedling stage in Population 250, year 5. Shaded bands correspond to 50% (darkest), 90%, 95% and 99.9% (lightest) credible intervals. Smaller intervals are not visible in the p-&gt;a transitions when the upper boundary of the interval is smaller than 0.01. Labels are median (lower 95% CI, upper 95% CI). Note that where the median and lower interval are equal to 0.001, the actual value is &lt; 0.001.
</p>
</div>
<p>Obtaining credible intervals on <span class="math inline">\(\lambda\)</span> requires simulation, because it is difficult (or maybe impossible) to use the characteristic equation to combine the probability distributions of the matrix entries to obtain the distribution of <span class="math inline">\(\lambda\)</span>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co">#71 popn 250 year 5 lambda = 0.93</span>
diffPriors_lci &lt;-<span class="st"> </span><span class="kw">list</span>()
samples =<span class="st"> </span><span class="dv">10000</span>
diffPriors_lci[[<span class="st">"Uniform"</span>]] &lt;-<span class="st"> </span><span class="kw">data_frame</span>(<span class="dt">A =</span> <span class="kw"><a href="../reference/sim_transitions.html">sim_transitions</a></span>(allA<span class="op">$</span>TF[[<span class="dv">71</span>]], 
                                                              allA<span class="op">$</span>N[[<span class="dv">71</span>]], 
                                                              <span class="dt">samples =</span> samples), 
                                          <span class="dt">lprior =</span> <span class="kw">map_dbl</span>(A, lambda))</code></pre></div>
<pre><code>## Warning in fill_fecundity(TF, N, alpha = alpha, beta = beta, priorweight =
## priorweight, : length(alpha) != order: only using first value of alpha and
## beta</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">diffPriors_lci[[<span class="st">"RLT, weight = 1"</span>]] &lt;-<span class="st"> </span><span class="kw">data_frame</span>(<span class="dt">A =</span> <span class="kw"><a href="../reference/sim_transitions.html">sim_transitions</a></span>(allA<span class="op">$</span>TF[[<span class="dv">71</span>]], allA<span class="op">$</span>N[[<span class="dv">71</span>]], 
                                                                      <span class="dt">P=</span>RLT_Tprior, 
                                                                      <span class="dt">alpha =</span> <span class="kw">c</span>(<span class="ot">NA_real_</span>, <span class="ot">NA_real_</span>, <span class="fl">0.025</span>),
                                                                      <span class="dt">beta =</span> <span class="kw">c</span>(<span class="ot">NA_real_</span>, <span class="ot">NA_real_</span>, <span class="dv">1</span>), 
                                                                      <span class="dt">samples =</span> samples), 
                                                  <span class="dt">lprior =</span> <span class="kw">map_dbl</span>(A, lambda))

diffPriors_lci[[<span class="st">"RLT, weight = 0.5N"</span>]] &lt;-<span class="st"> </span><span class="kw">data_frame</span>(<span class="dt">A =</span> <span class="kw"><a href="../reference/sim_transitions.html">sim_transitions</a></span>(allA<span class="op">$</span>TF[[<span class="dv">71</span>]], allA<span class="op">$</span>N[[<span class="dv">71</span>]], 
                                                                         <span class="dt">P=</span>RLT_Tprior,
                                                                         <span class="dt">alpha =</span> <span class="kw">c</span>(<span class="ot">NA_real_</span>, <span class="ot">NA_real_</span>, <span class="fl">0.025</span>),
                                                                         <span class="dt">beta =</span> <span class="kw">c</span>(<span class="ot">NA_real_</span>, <span class="ot">NA_real_</span>, <span class="dv">1</span>), 
                                                                         <span class="dt">priorweight =</span> <span class="fl">0.5</span>,
                                                                         <span class="dt">samples =</span> samples), 
                                                     <span class="dt">lprior =</span> <span class="kw">map_dbl</span>(A, lambda))

diffPriors_lci[[<span class="st">"RLT, weight = N"</span>]] &lt;-<span class="st"> </span><span class="kw">data_frame</span>(<span class="dt">A =</span> <span class="kw"><a href="../reference/sim_transitions.html">sim_transitions</a></span>(allA<span class="op">$</span>TF[[<span class="dv">71</span>]], allA<span class="op">$</span>N[[<span class="dv">71</span>]], 
                                                                      <span class="dt">P=</span>RLT_Tprior, 
                                                                      <span class="dt">alpha =</span> <span class="kw">c</span>(<span class="ot">NA_real_</span>, <span class="ot">NA_real_</span>, <span class="fl">0.025</span>),
                                                                      <span class="dt">beta =</span> <span class="kw">c</span>(<span class="ot">NA_real_</span>, <span class="ot">NA_real_</span>, <span class="dv">1</span>),
                                                                      <span class="dt">priorweight =</span> <span class="dv">1</span>,
                                                                      <span class="dt">samples =</span> samples), 
                                                  <span class="dt">lprior =</span> <span class="kw">map_dbl</span>(A, lambda))

diffPriors_lci &lt;-<span class="st"> </span><span class="kw">bind_rows</span>(diffPriors_lci, <span class="dt">.id=</span><span class="st">"prior"</span>)
diffPriors_lci<span class="op">$</span>prior &lt;-<span class="st"> </span><span class="kw">factor</span>(diffPriors_lci<span class="op">$</span>prior, <span class="dt">levels =</span> <span class="kw">c</span>(<span class="st">"Uniform"</span>, <span class="st">"RLT, weight = 1"</span>,
                                                        <span class="st">"RLT, weight = 0.5N"</span>, <span class="st">"RLT, weight = N"</span>))

<span class="kw">ggplot</span>(diffPriors_lci, <span class="kw">aes</span>(<span class="dt">x=</span>lprior)) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">geom_density</span>(<span class="dt">fill=</span><span class="st">"grey75"</span>) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">facet_wrap</span>(<span class="op">~</span>prior) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">theme_classic</span>() <span class="op">+</span><span class="st"> </span>
<span class="st">  </span>rlt_theme <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">xlab</span>(<span class="kw">expression</span>(<span class="kw">paste</span>(lambda,<span class="st">" asymptotic population growth"</span>))) <span class="op">+</span>
<span class="st">  </span><span class="kw">ylab</span>(<span class="st">"Posterior density"</span>)</code></pre></div>
<div class="figure">
<img src="transition_priors_files/figure-html/lambda_ci-1.png" alt="Distribution of asymptotic population growth rates for population 250, year 5, with different prior information." width="480"><p class="caption">
Distribution of asymptotic population growth rates for population 250, year 5, with different prior information.
</p>
</div>
</div>
<div id="references" class="section level1 unnumbered">
<h1 class="hasAnchor">
<a href="#references" class="anchor"></a>References</h1>
<div id="refs" class="references">
<div id="ref-eberhardt1986grizzly">
<p>Eberhardt, L. L., R. R. Knight, and B. M. Blanchard. 1986. “Monitoring Grizzly Bear Population Trends.” <em>The Journal of Wildlife Management</em> 50 (4). [Wiley, Wildlife Society]: 613–18. <a href="http://www.jstor.org/stable/3800971" class="uri">http://www.jstor.org/stable/3800971</a>.</p>
</div>
<div id="ref-morris2002quantitative">
<p>Morris, William F, Daniel F Doak, and others. 2002. “Quantitative Conservation Biology.” <em>Sinauer, Sunderland, Massachusetts, USA</em>.</p>
</div>
<div id="ref-SalgueroCompadre2015">
<p>Salguero-Gómez, Roberto, Owen R. Jones, C. Ruth Archer, Yvonne M. Buckley, Judy Che-Castaldo, Hal Caswell, David Hodgson, et al. 2015. “The compadrePlant Matrix Database: An Open Online Repository for Plant Demography.” <em>Journal of Ecology</em> 103 (1): 202–18. doi:<a href="https://doi.org/10.1111/1365-2745.12334">10.1111/1365-2745.12334</a>.</p>
</div>
<div id="ref-stott2010reducibility">
<p>Stott, Iain, Stuart Townley, David Carslake, and David J Hodgson. 2010. “On Reducibility and Ergodicity of Population Projection Matrix Models.” <em>Methods in Ecology and Evolution</em> 1 (3). Wiley Online Library: 242–52.</p>
</div>
<div id="ref-tremblay2003population">
<p>Tremblay, Raymond L, and Michael J Hutchings. 2003. “Population Dynamics in Orchid Conservation: A Review of Analytical Methods Based on the Rare Species Lepanthes Eltoroensis.” <em>Orchid Conservation, Borneo: Natural History Museum Publications</em>, 183–204.</p>
</div>
<div id="ref-tremblay2014bayesian">
<p>Tremblay, Raymond L, and Michael A McCarthy. 2014. “Bayesian Estimates of Transition Probabilities in Seven Small Lithophytic Orchid Populations: Maximizing Data Availability from Many Small Samples.” <em>PloS One</em> 9 (7). Public Library of Science: e102859.</p>
</div>
</div>
</div>
</div>
  </div>

  <div class="col-md-3 hidden-xs hidden-sm" id="sidebar">
        <div id="tocnav">
      <h2 class="hasAnchor">
<a href="#tocnav" class="anchor"></a>Contents</h2>
      <ul class="nav nav-pills nav-stacked">
<li><a href="#borrowing-strength">Borrowing strength</a></li>
      <li><a href="#the-matrix">The matrix</a></li>
      <li><a href="#ignore-the-problem">Ignore the problem</a></li>
      <li><a href="#fill-in-including-constraints-on-transitions">Fill in including constraints on transitions</a></li>
      <li><a href="#fill-in-using-uninformative-priors-on-fertility">Fill in using uninformative priors on fertility</a></li>
      <li><a href="#effects-of-informative-priors">Effects of informative priors</a></li>
      <li><a href="#obtaining-credible-intervals-on-vital-rates-and-lambda">Obtaining credible intervals on vital rates and <span class="math inline">\(\lambda\)</span></a></li>
      <li><a href="#references">References</a></li>
      </ul>
</div>
      </div>

</div>


      <footer><div class="copyright">
  <p>Developed by Andrew Tyre, Raymond Tremblay, Maria-Eglee Perez.</p>
</div>

<div class="pkgdown">
  <p>Site built with <a href="http://hadley.github.io/pkgdown/">pkgdown</a>.</p>
</div>

      </footer>
</div>

  </body>
</html>
