#' transition and recruitment data for \emph{L. elto}
#'
#' 6 month periodic census of several populations of the epiphytic Orchid \emph{Lepenthes elto}.
#'
#' \itemize{
#'    \item POPNUM...
#'    \item year...
#'    \item seedlings...
#'    \item adults...
#'    \item fertility...
#'    \item OCCUORNOT...
#'    \item REMOVEDORNOT...
#'    \item IND_NUM...
#'    \item stage...
#'    \item next_stage...
#'    \item first_year...
#'    \item last_year...
#'    \item recruited...
#'    \item died...
#'    \item lifespan...
#'  }
#'
#' @docType data
#' @export
#' @keywords ...
#' @name L_elto
#' @usage data(L_elto)
#' @format A data frame with 5233 rows and 15 variables
#' @source Raymond L. Tremblay, University of Puerto Rico, Unpublished data.
"L_elto"
